### ISSUE TITLE
Please provide additional information on how to configure

### ISSUE THREAD

**Issue by slomanl1** [sean6541/tuya-homeassistant#2]
Sean,
I am trying to use your https://github.com/sean6541/tuya-homeassistant Could you please provide me with an example of how the configuration should look? It is not clear whether or not single/double quotes need to be put around the name, host device_id or local_key fields. Furthermore, do I need to port forward port 6668 to the device ip address even if I am using it on the same wifi network as the homeassistant? Can the device_id and the local_key fields be either lowercase or uppercase? Here is my config: Please tell me if you see something wrong.

 switch:
   - platform: tuya
     name:  Jaffa Gate
     host: '192.168.0.26'
     local_key: 'FAE832B1EFBF97EB'
     device_id: '002006826001943A20E5'
     id:

**Comment by sean6541** [comment]
Use the device_id and local_key exactly as you see them. Do not use quotes on any of the fields. They are not necessary.

**Comment by sean6541** [comment]
Remove the id at the bottom.

**Comment by sean6541** [comment]
You should not need to do any port forwarding.

**Comment by sean6541** [comment]
Your config would look like:

```
switch:
   - platform: tuya
     name:  Jaffa Gate
     host: 192.168.0.26
     local_key: fae832b1efbf97eb
     device_id: 002006826001943a20e5
```
